apiVersion: v1
kind: Service
metadata:
  name: quiz-frontend
spec:
  type: ClusterIP 
  selector:
    app: quiz-frontend
  ports:
    - protocol: TCP
      port: 8080  
      targetPort: 80  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-frontend
  template:
    metadata:
      labels:
        app: quiz-frontend
    spec:
      containers:
      - name: quiz-frontend
        image: ghcr.io/domesday7/kapuut.quiz-frontend:latest
        ports:
        - containerPort: 8080
        env:
        - name: VITE_API_URL
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: ISTIO_URL
      imagePullSecrets:
        - name: ghcr-secret
    