apiVersion: v1
kind: Service
metadata:
  name: quiz-leaderboard
spec:
  type: ClusterIP 
  selector:
    app: quiz-leaderboard
  ports:
    - protocol: TCP
      port: 8080  
      targetPort: 8080  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-leaderboard
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: quiz-leaderboard
  template:
    metadata:
      labels:
        app: quiz-leaderboard
    spec:
      containers:
      - name: quiz-leaderboard
        image: ghcr.io/domesday7/kapuut.quiz-leaderboard:latest
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: DATABASE_URL
      imagePullSecrets:
        - name: ghcr-secret
    