apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: microservice-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kapuut-routes
spec:
  hosts:
    - "*"
  gateways:
    - microservice-gateway
  http:
    - match:
        - uri:
            prefix: /api/quiz
      rewrite:
        uri: /quiz
      route:
        - destination:
            port:
              number: 3100
            host: quiz-creator.default.svc.cluster.local

    - match:
      - uri:
          prefix: /socket
      route:
        - destination:
            port:
              number: 3000
            host: quiz-master.default.svc.cluster.local
          headers:
            request:
              set:
                Upgrade: websocket
                Connection: Upgrade

    - match:
        - uri:
            prefix: /api/leaderboard
      rewrite:
        uri: /leaderboard
      route:
        - destination:
            port:
              number: 8080
            host: quiz-leaderboard.default.svc.cluster.local

    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: quiz-frontend.default.svc.cluster.local
            port:
              number: 8080
